inherit_from: .rubocop_todo.yml

inherit_gem:
  bixby: bixby_default.yml
  
AllCops:
  TargetRubyVersion: 2.4

Layout/LineLength:
  Enabled: true
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/requests/absolute_id_request_spec.rb'
