---
locations:
  # URIs for ArchivesSpace location resources. For example:
  # - https://aspace.princeton.edu/locations/1

repositories:
  # URIs for ArchivesSpace repository resources. For example:
  # - https://aspace.princeton.edu/repositories/1

top_containers:
  # URIs for ArchivesSpace top container resources. For example:
  # - https://aspace.princeton.edu/repositories/1/top_containers/1
