locations:
  - label: 'Firestone Library'
    value: 'cotsen'
  - label: 'Firestone Library'
    value: 'ex'
  - label: 'Firestone Library'
    value: 'gax'
  - label: 'Firestone Library'
    value: 'ga'
  - label: 'Firestone Library'
    value: 'mss'
  - label: 'Firestone Library'
    value: 'njpg'
  - label: 'Firestone Library'
    value: 'thx'
  - label: 'Firestone Library'
    value: 'wa'
  - label: 'Firestone Library'
    value: 'hsvc'
  - label: 'Firestone Library'
    value: 'hsvg'
  - label: 'Firestone Library'
    value: 'hsvm'
  - label: 'Firestone Library'
    value: 'hsvr'
  - label: 'Mudd Manuscript Library'
    value: 'mudd'
  - label: 'ReCAP'
    value: 'rcppa'
  - label: 'ReCAP'
    value: 'rcppf'
  - label: 'ReCAP'
    value: 'rcpph'
  - label: 'ReCAP'
    value: 'rcpxc'
  - label: 'ReCAP'
    value: 'rcpxg'
  - label: 'ReCAP'
    value: 'rcpxm'
  - label: 'ReCAP'
    value: 'rcpxr'
  - label: 'ReCAP'
    value: 'selectors'
  - label: 'Firestone Library'
    value: 'flm'
  - label: 'Engineering Library'
    value: 'st'
  - label: 'Annex B'
    value: 'anxb'
  - label: 'Plasma Physics Library'
    value: 'ppl'
